/*
 * Hanja dictionary loading and lookup.
 *
 * This is the only part of libhangul that touches the filesystem, and it does
 * it in the way most likely to behave differently on Windows: hanja.c opens
 * the dictionary with fopen(path, "r") -- text mode -- records byte offsets
 * with ftell() during a first pass, and later fseek()s straight back to them
 * to read a group of entries. Under the MSVC CRT a text-mode stream collapses
 * CRLF on the way in, so ftell/fseek have to agree with each other about what
 * an offset means. A mismatch would not fail to compile and would not crash;
 * it would silently return the wrong hanja for a key. Hence a test.
 *
 * Three dictionaries are exercised:
 *   1. the real 6 MB engines/libhangul/data/hanja/hanja.txt, for a key far enough into
 *      the file that the recorded offset is large and the seek is real;
 *   2. a small generated dictionary with LF line endings;
 *   3. the same content with CRLF line endings.
 * (2) and (3) must give identical answers on both platforms -- that is the
 * whole point -- and they are written here in binary mode so the line endings
 * are exactly what this file says they are, not what the CRT prefers.
 *
 * argv[1]: path to hanja.txt.  argv[2]: a writable scratch directory.
 * Both are supplied by CMake; nothing here assumes /tmp or a path separator.
 *
 * Kept pure ASCII deliberately -- see the note in hangul_ic_test.c.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "hangul_test_util.h"

/* UTF-8 byte sequences. Written as escapes rather than literals so the file
 * means the same thing to a compiler that assumes an ANSI source encoding.
 * Every escape is followed by another escape or by ':', never by a hex digit,
 * so no \x runs on past its three bytes. */
#define K_GA      "\xEA\xB0\x80"                 /* U+AC00                */
#define K_GANA    "\xEA\xB0\x80\xEB\x82\x98"     /* U+AC00 U+B098         */
#define K_HANJA   "\xED\x95\x9C\xEC\x9E\x90"     /* U+D55C U+C790         */
#define V_GA_1    "\xE5\x8F\xAF"                 /* U+53EF                */
#define V_GA_2    "\xE5\xAE\xB6"                 /* U+5BB6                */
#define V_GANA    "\xE5\x81\x87\xE5\x90\x8D"     /* U+5047 U+540D         */
#define V_HANJA   "\xE6\xBC\xA2\xE5\xAD\x97"     /* U+6F22 U+5B57         */

/* Content of the generated dictionaries, one entry per element. Keys must be
 * in ascending byte order: hanja_table_load() builds a binary-searchable index
 * and hanja_table_match() stops as soon as the key stops matching. */
static const char* const small_dict_lines[] = {
    "# generated by libpathime's hangul.hanja test",
    K_GA ":" V_GA_1 ":comment-one",
    K_GA ":" V_GA_2 ":",              /* empty comment: a real case in hanja.txt */
    K_GANA ":" V_GANA ":comment-two",
    K_HANJA ":" V_HANJA ":comment-three"
};

/* Join <dir> and <name> with '/'. Windows accepts forward slashes throughout
 * the CRT, so one form works on both platforms. */
static void join_path(char* out, size_t outsz, const char* dir, const char* name)
{
    size_t n = strlen(dir);
    if (n + 1 + strlen(name) + 1 > outsz) {
        HT_FAILF("path buffer too small for %s/%s", dir, name);
        out[0] = '\0';
        return;
    }
    memcpy(out, dir, n);
    if (n > 0 && dir[n - 1] != '/' && dir[n - 1] != '\\')
        out[n++] = '/';
    /* memcpy rather than strcpy: MSVC deprecates the latter and this file has
     * no reason to add to the CRT-deprecation noise the vendored sources make. */
    memcpy(out + n, name, strlen(name) + 1);
}

/* Write the dictionary with the given line terminator. "wb" so the CRT does
 * not add a CR of its own on Windows and turn the LF variant into the CRLF
 * one. */
static int write_small_dict(const char* path, const char* eol)
{
    size_t i;
    FILE* f = fopen(path, "wb");
    if (f == NULL) {
        HT_FAILF("cannot create %s", path);
        return 0;
    }
    for (i = 0; i < sizeof(small_dict_lines) / sizeof(small_dict_lines[0]); i++) {
        fputs(small_dict_lines[i], f);
        fputs(eol, f);
    }
    fclose(f);
    return 1;
}

/* Assert that <list> holds exactly the given key/value pairs, in order. */
static void expect_entries(const char* what, const HanjaList* list,
                           const char* const* keys, const char* const* values,
                           int n)
{
    int i;

    ht_checks++;
    if (hanja_list_get_size(list) != n) {
        HT_FAILF("%s: expected %d entries, got %d", what, n,
                 hanja_list_get_size(list));
        return;
    }
    for (i = 0; i < n; i++) {
        const char* k = hanja_list_get_nth_key(list, (unsigned)i);
        const char* v = hanja_list_get_nth_value(list, (unsigned)i);
        ht_checks++;
        if (k == NULL || v == NULL || strcmp(k, keys[i]) != 0
            || strcmp(v, values[i]) != 0) {
            HT_FAILF("%s: entry %d is %s/%s, expected %s/%s", what, i,
                     k ? k : "(null)", v ? v : "(null)", keys[i], values[i]);
        }
    }
}

/* --- the shipped dictionary --------------------------------------------- */
static void test_real_dictionary(const char* path)
{
    HanjaTable* table;
    HanjaList* list;
    int i, n;

    table = hanja_table_load(path);
    HT_CHECK(table != NULL);
    if (table == NULL) {
        HT_FAILF("could not load %s -- the rest of this group is skipped", path);
        return;
    }

    /* U+D55C U+C790 sits roughly 280k lines into the file, so the offset the
     * loader recorded for it is a large one and the fseek is not a no-op. */
    list = hanja_table_match_exact(table, K_HANJA);
    HT_CHECK(list != NULL);
    n = hanja_list_get_size(list);
    /* Deliberately a lower bound rather than an exact count: the dictionary is
     * vendored data that upstream may add to. A wrong *seek* shows up as zero
     * entries or as entries under a different key, both of which are caught. */
    HT_CHECK(n >= 3);
    for (i = 0; i < n; i++) {
        const char* k = hanja_list_get_nth_key(list, (unsigned)i);
        ht_checks++;
        if (k == NULL || strcmp(k, K_HANJA) != 0) {
            HT_FAILF("real dict: entry %d has key %s, expected the search key",
                     i, k ? k : "(null)");
            break;
        }
    }
    if (n >= 1) {
        const char* v = hanja_list_get_nth_value(list, 0);
        HT_CHECK(v != NULL && strcmp(v, V_HANJA) == 0);
        /* comments in hanja.txt are frequently empty; never NULL */
        HT_CHECK(hanja_list_get_nth_comment(list, 0) != NULL);
    }
    HT_CHECK(hanja_list_get_key(list) != NULL
             && strcmp(hanja_list_get_key(list), K_HANJA) == 0);
    hanja_list_delete(list);

    /* A key that is not in the dictionary must give NULL, and the accessors
     * must tolerate it -- ibus engines call get_size() on the result directly. */
    list = hanja_table_match_exact(table, "zzzz-not-a-hangul-key");
    HT_CHECK(list == NULL);
    HT_CHECK(hanja_list_get_size(list) == 0);
    hanja_list_delete(list);

    hanja_table_delete(table);
}

/* --- generated dictionaries, LF and CRLF -------------------------------- */
static void test_generated_dictionary(const char* path, const char* label)
{
    static const char* const ga_keys[]   = { K_GA, K_GA };
    static const char* const ga_values[] = { V_GA_1, V_GA_2 };
    static const char* const gana_keys[]   = { K_GANA, K_GA, K_GA };
    static const char* const gana_values[] = { V_GANA, V_GA_1, V_GA_2 };

    HanjaTable* table;
    HanjaList* list;

    table = hanja_table_load(path);
    HT_CHECK(table != NULL);
    if (table == NULL) {
        HT_FAILF("%s: could not load %s", label, path);
        return;
    }

    /* exact match: the comment line at the top must have been skipped without
     * throwing the recorded offsets off by its length */
    list = hanja_table_match_exact(table, K_GA);
    expect_entries(label, list, ga_keys, ga_values, 2);
    if (hanja_list_get_size(list) == 2) {
        const char* c0 = hanja_list_get_nth_comment(list, 0);
        const char* c1 = hanja_list_get_nth_comment(list, 1);
        HT_CHECK(c0 != NULL && strcmp(c0, "comment-one") == 0);
        /* the second entry's comment field is empty in the source */
        HT_CHECK(c1 != NULL && strcmp(c1, "") == 0);
    }
    hanja_list_delete(list);

    /* prefix match walks the key back one character at a time, so it visits
     * two distinct file offsets */
    list = hanja_table_match_prefix(table, K_GANA);
    expect_entries(label, list, gana_keys, gana_values, 3);
    hanja_list_delete(list);

    list = hanja_table_match_exact(table, K_HANJA);
    HT_CHECK(hanja_list_get_size(list) == 1);
    hanja_list_delete(list);

    hanja_table_delete(table);
}

int main(int argc, char* argv[])
{
    char lf_path[1024];
    char crlf_path[1024];

    if (argc < 3) {
        fprintf(stderr, "usage: %s <hanja.txt> <scratch-dir>\n", argv[0]);
        return 2;
    }

    /* A path that does not exist must be reported, not crashed on. */
    HT_CHECK(hanja_table_load("./no-such-hanja-dictionary.txt") == NULL);
    hanja_table_delete(NULL);

    test_real_dictionary(argv[1]);

    join_path(lf_path, sizeof(lf_path), argv[2], "hanja-lf.txt");
    join_path(crlf_path, sizeof(crlf_path), argv[2], "hanja-crlf.txt");

    if (write_small_dict(lf_path, "\n"))
        test_generated_dictionary(lf_path, "generated dict (LF)");
    if (write_small_dict(crlf_path, "\r\n"))
        test_generated_dictionary(crlf_path, "generated dict (CRLF)");

    return ht_report("hangul.hanja");
}
