#!/usr/bin/env python3
"""Regenerate src/engines/table/variants_data.h from Unicode's Unihan_Variants.txt.

docs/ibus-table-mapping.md §11.1 classifies a candidate's first character as
simplified, traditional, or both, and §13.4 requires that table to be
regenerated from upstream Unicode data rather than copied from ibus-table's
generated one. This is that regeneration.

The classification rule, which is the whole of the logic:

  * A character carrying kTraditionalVariant *has* a traditional form, so it is
    itself a simplified form: simplified-only.
  * A character carrying kSimplifiedVariant *has* a simplified form, so it is
    itself a traditional form: traditional-only.
  * A variant field pointing at the character itself means "unchanged by
    simplification" and is ignored, which is why the self-reference test is not
    an optimization but part of the rule.
  * A character carrying both, or neither, belongs to both scripts. Most Han
    characters are in the second group -- they were never simplified -- which is
    why the emitted table lists only the exceptions.

Run it when moving to a newer Unicode release:

    python3 tools/generate-variants.py path/to/Unihan_Variants.txt \\
        > src/engines/table/variants_data.h

Unihan_Variants.txt is part of the Unicode Character Database; it is not
vendored here, because the generated table is the artifact this library needs
and regenerating is a once-a-release operation.
"""

import sys
import re

SIMPLIFIED = 1
TRADITIONAL = 2
BOTH = SIMPLIFIED | TRADITIONAL

CODEPOINT = re.compile(r"U\+([0-9A-Fa-f]+)")


def classify(path):
    """Map code point -> mask, for the characters that are not simply BOTH."""
    has_traditional_form = set()
    has_simplified_form = set()

    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("#"):
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 3:
                continue

            code, field, value = fields[0], fields[1], fields[2]
            if field not in ("kSimplifiedVariant", "kTraditionalVariant"):
                continue

            match = CODEPOINT.fullmatch(code)
            if not match:
                continue
            point = int(match.group(1), 16)

            # A field listing only the character itself says it is unchanged by
            # simplification, which tells us nothing about which script it
            # belongs to.
            targets = {int(m, 16) for m in CODEPOINT.findall(value)}
            targets.discard(point)
            if not targets:
                continue

            if field == "kTraditionalVariant":
                has_traditional_form.add(point)
            else:
                has_simplified_form.add(point)

    masks = {}
    for point in has_traditional_form | has_simplified_form:
        mask = BOTH
        if point in has_traditional_form and point not in has_simplified_form:
            mask = SIMPLIFIED
        elif point in has_simplified_form and point not in has_traditional_form:
            mask = TRADITIONAL
        if mask != BOTH:
            masks[point] = mask
    return masks


def ranges(masks):
    """Coalesce the point->mask map into (first, last, mask) runs."""
    out = []
    for point in sorted(masks):
        mask = masks[point]
        if out and out[-1][2] == mask and out[-1][1] == point - 1:
            out[-1][1] = point
        else:
            out.append([point, point, mask])
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: generate-variants.py Unihan_Variants.txt")

    masks = classify(sys.argv[1])
    table = ranges(masks)

    write = sys.stdout.write
    write("/*\n")
    write(" * Generated by tools/generate-variants.py from Unicode's\n")
    write(" * Unihan_Variants.txt. Do not edit; see docs/ibus-table-mapping.md §11.1\n")
    write(" * for what the masks mean and §13.4 for why this is regenerated rather\n")
    write(" * than copied.\n")
    write(" *\n")
    write(" * Every Han character not listed here belongs to both scripts, which is\n")
    write(" * the overwhelming majority: only characters simplification actually\n")
    write(" * changed appear below.\n")
    write(" */\n\n")
    write("#ifndef LIBPATHIME_SRC_ENGINES_TABLE_VARIANTS_DATA_H\n")
    write("#define LIBPATHIME_SRC_ENGINES_TABLE_VARIANTS_DATA_H\n\n")
    write("#include <cstdint>\n\n")
    write("namespace pathime {\n")
    write("namespace table {\n\n")
    write("struct VariantRange {\n")
    write("    uint32_t first;\n")
    write("    uint32_t last;\n")
    write("    uint8_t mask;\n")
    write("};\n\n")
    write("constexpr VariantRange kVariantRanges[] = {\n")
    for first, last, mask in table:
        write("    {0x%04X, 0x%04X, %d},\n" % (first, last, mask))
    write("};\n\n")
    write("constexpr size_t kVariantRangeCount =\n")
    write("    sizeof(kVariantRanges) / sizeof(kVariantRanges[0]);\n\n")
    write("}  // namespace table\n")
    write("}  // namespace pathime\n\n")
    write("#endif /* LIBPATHIME_SRC_ENGINES_TABLE_VARIANTS_DATA_H */\n")


if __name__ == "__main__":
    main()
